version: '2'

services:
  gl-switch:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gl-switch.loadbalancer.server.port=8080"
      - "traefik.http.routers.gl-switch.entrypoints=http"
      - "traefik.http.routers.gl-switch.rule=Host(`resolve.sd.di.huc.knaw.nl`)"
    networks:
      - traefik-public
networks:
  traefik-public:
    external:
      name: traefik-public
