- recipe: nl.knaw.huc.sdswitch.recipe.handle.HandleRecipe
  urls:
    - pattern: /hdl:{prefix}/{suffix}
      accept: text/html
    - pattern: /hdl:{prefix}/{suffix}.html
- recipe: nl.knaw.huc.sdswitch.recipe.handle.S3Recipe
  urls:
    - pattern: /hdl:{prefix}/place:{uuid}
      accept: application/json
    - pattern: /hdl:{prefix}/place:{uuid}.json
